global.statsObject = {
	"Points de vie": (50 + 5 * 200),
	"Portée": 0,
	"Prospection": 100,
	"Initiative": 0,
	"Invocation": 1,
	"Soin": 0,
	"Vitalité": 0,
	"Sagesse": 0,
	"Force": 0,
	"Intelligence": 0,
	"Chance": 0,
	"Agilité": 0,
	"Puissance": 0,
	"Fuite": 0,
	"Tacle": 0,
	"Esquive PA": 0,
	"Esquive PM": 0,
	"Retrait PA": 0,
	"Retrait PM": 0,
	"PA": 7,
	"PM": 3,
	"Dommages Neutre": 0,
	"Dommages Terre": 0,
	"Dommages Feu": 0,
	"Dommages Eau": 0,
	"Dommages Air": 0,
	"Dommages Critique": 0,
	"Dommages Poussée": 0,
	"Dommages Mélée": 0,
	"Dommages Distance": 0,
	"Dommages d'Armes": 0,
	"Dommages aux Sorts": 0,
	"% Résistance Neutre": 0,
	"% Résistance Terre": 0,
	"% Résistance Feu": 0,
	"% Résistance Eau": 0,
	"% Résistance Air": 0,
	"Résistance Neutre": 0,
	"Résistance Terre": 0,
	"Résistance Feu": 0,
	"Résistance Eau": 0,
	"Résistance Air": 0,
	"Résistance Critique": 0,
	"Critique": 0,
	"Résistance Poussée": 0,
	"Dommages Piège": 0,
	"Puissance Piège": 0,
	"Renvoi Dommages": 0,
	"Résistance Mélée": 0,
	"Résistance Distance": 0,
	"Résistance d'Armes": 0,
	"Résistance aux Sorts": 0
};

global.actualStuff = {
	amulette: null,
	coiffe: null,
	bouclier: null,
	cac: null,
	anneau1: null,
	anneau2: null,
	ceinture: null,
	cape: null,
	bottes: null,
	familier: null,
	dofus: [null, null, null, null, null, null],
	classe: null,
	sexe: 0,
	stats: statsObject,
};
